FROM pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime

COPY ./requirements.txt /tmp/

RUN cd /tmp && \
    pip config set global.index-url https://mirrors.aliyun.com/pypi/simple && \
    pip install --no-cache-dir -U pip && \
    pip install --no-cache-dir -r requirements.txt