version: "3.8"

services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - vinda-redis-vol:/data
    command: redis-server

volumes:
  vinda-redis-vol:
